apiVersion: v1
kind: Service
metadata:
  name: ugonnawinms-slack-validator-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: ${PORT}
  selector:
    app: ugonnawinms-slack-validator